$(function(){

    //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        // 1  1  2  3  5   8  

    //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.

    let fibonacciArry = [1, 2];
    // let evenNum = [];
    let total;
    let evenNum = 2;

    for (i=0; i < 10; i++) {
        let numlengh = fibonacciArry.length
        firstNum = fibonacciArry[numlengh - 2];
        secondNum = fibonacciArry[numlengh -1];

        newNum = firstNum + secondNum;

        fibonacciArry[numlengh] = newNum;

        console.log(fibonacciArry);

        if (newNum % 2 === 0) {
            evenNum =+ newNum;
        }
    }
    console.log(evenNum);

});